title: Visual Studio Extensibility Cookbook
description: The Visual Studio Extensibility Cookbook 
#theme: jekyll-theme-tactile
layout: default

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
    style: compressed