title: Visual Studio Extensibility Cookbook
description: Visual Studio Extensibility Cookbook 
#theme: jekyll-theme-tactile
layout: default

css:
  syntax: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
    style: compressed